### ISSUE TITLE
Bad thumbnails quality

### ISSUE THREAD

**Issue by Genhis** [awthwathje/SteaScree#1]
First of all, I want to say it's a great tool! I wanted to create something similar when I found yours.

It works very well for me, but it seems to me that a quality of thumbnails is bad. I would suggest to use an algorithm that produces smoother results.

Thank You.

**Comment by awthwathje** [comment]
Hello. Thanks for kind words.

Well, the truth is, thumbnail quality is almost exactly what Steam produces: 95% JPEG. I've compared Steam's own thumbnails of the same screenshot with thumbnail which SteaScree has produced and found out that both the size and level details are the same. So I think Steam also uses 95% JPEG.

I can make it 100% JPEG, but honestly the quality bump will be next to nothing, but the size will significantly increase.

However, if you'd like to make your own investigation on the issue and give me some comparison image examples, I'd look into this problem more.

**Comment by Genhis** [comment]
I don't think the problem is in the quality, but in the algorithm that scales an image. Much better results are with cubic interpolation. (I suppose you're scaling an image without interpolation.)

I'm attaching two pictures - first, how it should be; second, created by your program.

![cubic_interpolation](https://cloud.githubusercontent.com/assets/11155942/19380364/42e88bd2-91f7-11e6-8843-8963019157f2.jpg)
![no_interpolation](https://cloud.githubusercontent.com/assets/11155942/19380363/42e3dd76-91f7-11e6-92e3-452e5f35a550.jpg)

**Comment by awthwathje** [comment]
Got it. Can you please share the original image so I can experiment with it?

**Comment by Genhis** [comment]
Sure. :-)

![20161009112322_1](https://cloud.githubusercontent.com/assets/11155942/19386066/872dfa96-9212-11e6-930f-d3bc4c06bf01.jpg)
