### ISSUE TITLE
"none of the screenshots were copied" on v 1.4.1-Linux-x64

### ISSUE THREAD

**Issue by TheDaviot** [awthwathje/SteaScree#11]
![steascreelinuxissue](https://cloud.githubusercontent.com/assets/27928675/25317380/481632b2-283d-11e7-91e8-ee954792b5ab.png)

On launching the Linux version via bash, it returns the following comment on launching:
"QApplication: invalid style override passed, ignoring it."

The program runs, and finds the right directory for Steam automatically. 
However, on clicking Copy Screenshots, "none of screenshots were copied" appears in red text, and both the queue disappears and all buttons grey out and become nonresponsive until the program is closed.

Running Steam and SteaScree on Linux Mint 18.1, which uses Ubuntu 16.04 LTS as a base.

**Comment by awthwathje** [comment]
Okay, let's debug this one. Please answer the following questions.

1. How program is started (what exact Bash command)?
2. Are there any files in the screenshots folder?
3. Have you checked if your screenshots.vdf is causing problems ([here is how](http://steamcommunity.com/groups/steascree/discussions/0/133259227512594351/))?

**Comment by TheDaviot** [comment]
1. Opened terminal to the extracted SteaScree folder, then "bash SteaScree.sh".  This time around, it was slightly more verbose:
![steascreeterminal](https://cloud.githubusercontent.com/assets/27928675/25600708/c0140860-2eab-11e7-8103-0cf60879d7b0.png)

2. Originally, yes to having a screenshots folder, no to there being screenshots in that game's folder.  I uploaded the original screenshots in question using the Windows version, and on attempting to upload new screenshots for the same game, the Linux version now worked:
![steascreeready](https://cloud.githubusercontent.com/assets/27928675/25600864/f5a4791e-2eac-11e7-87f8-5f629a594000.png).

3. Yup.  I backed up the screenshots.vdf before I started using SteaScree and followed the directions.

Will follow with attempts to recreate the issue...

**Comment by TheDaviot** [comment]
Hrrg, whatever weird roadblock I hit the first time around appears to be straightened out to the point that I've been unable to reproduce it.  Things tried include:

-Prepping screenshots for games not installed/not available on Linux with the Linux version of SteaScree.
-Prepping screenshots for games I've never uploaded screenshots for.
-Deleting screenshots.vdf, forcing Steam to rebuild it.
-Deleting a game's screenshots folder and then manually entering it.
-Manually placing in screenshots folder a .jpg file named like a Steam screenshot (but not referenced in the .vdf index) and then attempting to upload it in Steam (creating a SteamCloud error)
-Deleting the entire SteaScree folder, re-extracting it from the archive and rerunning.
-Intentionally pointing SteaScree to a bad location for Steam user data.

All I can deduce was there was some quirk in either of the .vdf files that the Linux version somehow didn't like, but that the Windows version happily ignored, as after using the Windows version successfully once, I've been unable to reproduce the error on the Linux side with the same Steam account.

**Comment by TheDaviot** [comment]
Okay, update, it was actually repeating the same error, just not giving the same feedback within SteaScree.  The program reports a success on copying the files, but does not _actually_ copy them:
![steascree-nonecopied](https://cloud.githubusercontent.com/assets/27928675/25607804/d43d80a0-2edd-11e7-8049-a477908f9954.jpg)
Rather than greying out the window, instead, the "Prepare" button becomes selectable, and if used, adds the screenshots's filenames to screenshots.vdf, but when opened upon rebooting Steam, show filesizes of 0 and error placeholder images:
![steascree-steam-pic_could_not_be_loaded](https://cloud.githubusercontent.com/assets/27928675/25607902/50c14b84-2ede-11e7-8ff8-e165105b7ebd.jpg)
Clearing out the folder and reloading or rebuilding screenshots.vdf doesn't affect the end result, as SteaScree creates the appropriate folder but never copies the selected screenshots to the new folder.

**Comment by awthwathje** [comment]
Well, the proper script to run is _Start SteaScree.sh_. It makes SteaScree ignore Mint-provided Qt libraries and use those distributed within the archive. Could you please to run it and check if the issue persists?

I mean, you can just `cd` into the unpacked directory and then fire `./Start SteaScree.sh`. No need to summon `bash` since this script is a plain `sh`.

**Comment by awthwathje** [comment]
I've just installed Mint 18.1, Steam and SteaScree and I was able to reproduce the "none of the screenshots were copied" error. Seems like this is Mint-specific, since various versions of Ubuntu work well. I will check what went wrong.
Thanks for reporting, I think I'll fix this bug this or the next week.

**Comment by awthwathje** [comment]
I figured out what is wrong. Qt's _imageformats_ directory with a whole variety of image-processing libraries (such as _libqjpeg.so_) should be distributed with the app. Some distributions (such as Ubuntu) don't require it though.

I've updated the archive for Linux, feel free to [download it](https://steascree.download). I've tested it on Mint 18.1, it works pretty well.

Don't forget, that you should start it by running `./Start SteaScree`.

**Comment by TheDaviot** [comment]
Confirming that the 10 May 2017 update appears to have fixed this issue on Linux Mint 18.1:
http://steamcommunity.com/sharedfiles/filedetails/?id=923370037

**Comment by awthwathje** [comment]
Great, thanks for your time reporting that the issue has been resolved.
