### ISSUE TITLE
Custom screenshot appears to upload, then "steam cloud may be temporarily unavailable"

### ISSUE THREAD

**Issue by sifkitty3** [awthwathje/SteaScree#12]
Pretty self-explanatory. Using Antergos 17.6 64-bit, Linux 4.10.13-1-ARCH.
Whenever I try to prepare a screenshot, it appears to work, and the screenshot and vdf file look correct, and the screenshot appears in the Screenshot Uploader with the correct thumbnail. However, when I add in my caption and press "Upload", it looks as if it uploads fine, then it shows the "steam cloud may be temporarily unavailable" message as shown below. This happens with every attempt, with a clean vdf/screenshots folder as well.

![pstyy9l](https://cloud.githubusercontent.com/assets/25442814/25834548/3571c8e2-3468-11e7-839f-b909f01e4819.png)

**Comment by awthwathje** [comment]
Hey. Where can I download Antergos 17.6? I see only 17.5 on the official site.

**Comment by sifkitty3** [comment]
Sorry, I mistyped. I meant 17.5

**Comment by awthwathje** [comment]
No problem. I'll look into it when I have time.

**Comment by awthwathje** [comment]
From the screenshot you provided it appears that the file in question is actually in the proper directory. So probably the corresponding entry in the _screenshots.vdf_ is somewhat faulty. Please share your screenshots.vdf so I can try to inspect it.

**Comment by awthwathje** [comment]
Closing this since there is no answer from the submitter.
