### ISSUE TITLE
Steam userdata directory is not found

### ISSUE THREAD

**Issue by sey4eto** [awthwathje/SteaScree#13]
Got this error - "Steam userdata directory is not found". 

![untitled](https://cloud.githubusercontent.com/assets/28564856/25850932/e1ede966-34cc-11e7-9abb-79c908326158.png)

Then i manually locate userdata folder then program crashes with "SteaScree: Steam Cloud Screenshot Uploader has stopped working". 

![untit222led](https://cloud.githubusercontent.com/assets/28564856/25851128/2f124d5e-34cd-11e7-8b6e-a4b04547d203.png)

Im on Win10 with Windows Defender.

**Comment by awthwathje** [comment]
1. What is the full path to the userdata folder?
2. Have you tried to create a mock Steam directory with userdata folder inside and point SteaScree to it?

**Comment by awthwathje** [comment]
Closing this since there is no answer from the submitter.

**Comment by 0xpr03** [comment]
Same problem here on linux, though it doesn't crash, it just does nothing & stays on "not found".
Ubuntu 18.04

**Comment by awthwathje** [comment]
> Same problem here on linux, though it doesn't crash, it just does nothing & stays on "not found".
> Ubuntu 18.04

Can you please file another bug so I'll be able to follow up? I don't guarantee it'll be soon, since I'm extremely busy lately, but still.
