### ISSUE TITLE
"none of screenshots were copied" - Windows 10

### ISSUE THREAD

**Issue by D-ster** [awthwathje/SteaScree#14]
This was my first time using this program and I was putting two images inside the program, one of them was 506x929 and the other was 100x929. 
<img width="336" alt="capture" src="https://cloud.githubusercontent.com/assets/28845734/26286717/f9789e34-3e39-11e7-95d9-5b6b37d10457.PNG">
However, as soon as I clicked "Copy screenshots to game directory" I got this.
<img width="336" alt="0capture" src="https://cloud.githubusercontent.com/assets/28845734/26286725/1aacbe14-3e3a-11e7-8292-fd8b288f92db.PNG">
I've tried this five times now with no new result, is there any tips you guys can give me?

**Comment by awthwathje** [comment]
From what I see on the screenshots you provided, the app looks strange. Do you use latest version?

**Comment by awthwathje** [comment]
Closing as there is no feedback from the submitter.
