### ISSUE TITLE
<Someone that is not you>

### ISSUE THREAD

**Issue by ghost** [awthwathje/SteaScree#15]
I only have 1 account and have only used 1 account. I click the dropdown and nothing else is selectable. Any screenshot I try to copy to game directory just says "None of screenshots were copied."

![qewf](https://user-images.githubusercontent.com/29674401/27508104-0c70f5fc-58a4-11e7-8c79-6ae23b197e6e.png)

**Comment by awthwathje** [comment]
Please try this procedure to check if your _screenshots.vdf_ file is preventing SteaScree from working correctly: http://steamcommunity.com/groups/steascree/discussions/0/133259227512594351/

If not, I'll try to investigate your case.

**Comment by ghost** [comment]
Just tried that and nothing changed.
EDIT: Should've included this is Windows 8.1

**Comment by awthwathje** [comment]
Okay, please share your _screenshots.vdf_.

**Comment by awthwathje** [comment]
Closed because of a lack of feedback from the submitter.
