### ISSUE TITLE
Steam cloud may be temporarily unavailable?

### ISSUE THREAD

**Issue by himaritf** [awthwathje/SteaScree#18]
So I read some info about this tool and found that people are using this in order to circumvent this cloud issue. However, I downloaded this tool to upload screenshots for a game that does not support overlay. After clicking "prepare screenshots for uploading" and restarting steam, I received the "Steam cloud may be temporarily unavailable" error when trying to upload screenshots, which never happened before using this tool. Is there any way I can fix this or revert to a state before I used the tool?

**Comment by awthwathje** [comment]
Basically, SteaScree modifies your _screenshots.vdf_, and it [backs up](https://github.com/Foyl/SteaScree/blob/110bfd1ee6052d4420ff8d9931fc3bbea0aa4e98/controller.cpp#L468) the initial version of this file before making any changes to it.

You can search for the _screenshots.vdf.bak_ in your Steam folder, move to the directory when it is found, remove _screenshots.vdf_ there and rename _screenshots.vdf.bak_ to _screenshots.vdf_. That's how you revert it to pre-SteaScree state.

This will work only if you used SteaScree once. If you used it twice or more, _screenshots.vdf.bak_ will not be of a pre-SteaScree version.

**Comment by himaritf** [comment]
Unfortunately I used the tool more than once. Is there any way for me to be able to upload screenshots again? I seem to get the error no matter what I try to upload onto the steam cloud.

**Comment by awthwathje** [comment]
Well, if you already have your screenshots uploaded to the Steam Cloud, you may remove the _screenshots.vdf_ file altogether. It will be recreated by Steam when you'll make some screenshots using Steam's own in-game overlay.
