### ISSUE TITLE
QObject and QMainWindow classes aren't included with the source code.

### ISSUE THREAD

**Issue by n00bdragon** [awthwathje/SteaScree#2]
Can't compile the code as downloaded.

**Comment by awthwathje** [comment]
Hello. To compile this project, you should install Qt before. Latest SteaScree works with latest Qt as of October 2016: 5.7.0. You can download it here for free: https://www.qt.io/download-open-source/#section-2
Once downloaded, use included Qt Creator tool to import and compile the project, or build it manually from the console.
