### ISSUE TITLE
There was an error uploading 1 screenshots.  Steam Cloud may be temporarily unavailable.

### ISSUE THREAD

**Issue by MissaCazuri** [awthwathje/SteaScree#20]
I tried using the program in a game where steam overlay is not working. After doing everything fine, this message keeps popping up rendering my ability to upload any screenshot tho I can still upload artworks. I've read the previous similar close thread but the guy Im taking to insist I file the issue here. Hope I can get any help

**Comment by awthwathje** [comment]
Hello. Please answer the following questions to clarify things a bit.

1. Which OS you use?
2. Do you own the game you try to upload screenshots for?
3. How do you choose the game ID (selecting from the dropdown or type-in directly)?
4. Are you able to upload screenshots for other games in a regular Steam way?

**Comment by MissaCazuri** [comment]
1. Win 10
2. Yes
3. I did select the game ID by selecting from the dropdown
4. I cant upload any screenshot from any games after using the program but I can still upload any artwork from that specific account. When I change to my alternative account, I can upload any screenshot from any game.

**Comment by awthwathje** [comment]
Well, you need to figure out why you can't regularly upload screenshots from the affected account first. Remove _screenshots.vdf_ file from that account's folder, make a screenshot for some game in a regular way with Steam and upload it. Steam will then recreate _screenshots.vdf_ file.

After that successful regular upload, you can try to use SteaScree with this account. It will probably work this time.

**Comment by MissaCazuri** [comment]
I didnt do anything yet but I can upload screenshot but I cant upload the screenshot that was added by SteaScree. The game has no steam overlay support so I just normaly screenshot a scene from the game and I use SteaScree to add that screenshot so I can upload it. Can I do something about this? the problem now is I cant upload the screenshots added by SteaScree

**Comment by awthwathje** [comment]
Wait, you just commented: _"4. I cant upload any screenshot from any games after using the program ..."_. And now you're saying that you can actually "upload screenshot".

So, what is the case actually?

1. You can upload in a regular Steam way (with the use of overlay), but can't do this with SteaScree.
or
2. You can't upload screenshots taken either with overlay or SteaScree.

What is better describes your situation?

**Comment by MissaCazuri** [comment]
This is a long ass story but it seems you need it to understand whats going on.

First Im playing a game called Governor of Poke 2 in steam, The game doesnt support steam overlay. Im planning to post a screenshot, upon researching I stumbled across this program called SteaScree, pretty easy and the interface is easy to understand so I give it a try. Before I used the program called SteaScree I can upload normal screenshot from any game. After I used the program I stumbled across an error which is the There was an error uploading 1 screenshots. Steam Cloud may be temporarily unavailable. Now after this incident I cant upload any screenshot from any game. Before I saw a thread saying I can delete the screenshots.vdf and rename the other that has .bak a friend of mine already help me and he arrived at the same conclusion but instead of deleting those two he suggest just to change the directory which I did and he also said that reinstall SteaScree might help which also I did. This didnt work either, I still encounter the error. I ask a person in steam for a quick remedy about this but he said there is not so he said I should post here which I did. Now after almost a day after I got home, I answered your initial question before testing whether I can upload any screenshot or not. After doing some dailies in some of my games I tried uploading a screenshot which work but the error pop-ups if I tried to upload the screenshot added by SteaScree. So now Im here asking for help what should I do so i can upload the screenshot added by SteaScree.  To answer your question 1.  Yes, I can upload any screenshot taken with the use of overlay but cant upload any screenshot added by SteaScree note that the game Im trying to add the screenshot doesnt support steam overlay so this might be a factor. I hope this help sorry for the long essay.

**Comment by awthwathje** [comment]
Okay, I understood that you currently have no problems with uploading overlay-taken screenshots for any Steam game you own, but for some reason Steam refuses to upload SteaScree-prepared screenshots.

Can you share your _screenshots.vdf_ file and specify game id for the game in question?

**Comment by MissaCazuri** [comment]
I cant upload the vdf file here so here's a google link (https://drive.google.com/open?id=1vmbDDz3S4_nEJTEsDfHNXc7D45k0Oqwb) and the game ID is 70200, the game is called Governor of Poker 2

**Comment by awthwathje** [comment]
So, you have a couple of screenshots registered for this game (70200). Can you please remove them via Steam Screenshot Uploader, then restart Steam, exit it and try to upload some screenshot for this game via SteaScree one more time?

**Comment by MissaCazuri** [comment]
https://i.imgur.com/c4kFBES.png
Still an error

**Comment by MissaCazuri** [comment]
and now I cant upload any screenshot for any game, so its back to the initial problem. It might resolve itself if I wait like what I did

**Comment by awthwathje** [comment]
Isn't Governor of Poker 2: Premium Edition's game ID in Steam is `70210`?

**Comment by MissaCazuri** [comment]
but you can see here that it says 70200 https://i.imgur.com/J3zBz8D.png

**Comment by awthwathje** [comment]
Actually there are two games with different IDs:
1. Governor of Poker 2 — ID: 70200
2. Governor of Poker 2 - Premium Edition — ID: 70210.

You appear to own 70210 and not 70200.

In its dropdown SteaScree shows the games for which screenshots were previously uploaded (successfully or not). IDs can change over time, but SteaScree knows nothing about it.

So, if any issues, you should double-check if you really own the game with the ID you trying to use.

Now, please type-in `70210` ID directly into SteaScree's "Game ID" field (don't select the existing entry) and try to upload some screenshots for it. If everything is okay this time, please comment here or close this issue.

**Comment by MissaCazuri** [comment]
I tried it but it the error still persist, I might wanna wait some time then try it again

**Comment by awthwathje** [comment]
So, you've just tried to upload some screenshots to `70210`? Can you please re-share your _screenshots.vdf_ so I can check if the entry was successfully added?

**Comment by MissaCazuri** [comment]
https://drive.google.com/open?id=1vmbDDz3S4_nEJTEsDfHNXc7D45k0Oqwb

**Comment by awthwathje** [comment]
Seems like the entry was properly added to the file. But this game is location-restricted, for example I can't see it in Steam's Store. 

Do you see the game's page properly at the address http://store.steampowered.com/app/70210? Without the use of proxies.

**Comment by MissaCazuri** [comment]
I can see the game properly without proxies, https://i.imgur.com/xL9MCgE.jpg. Any suggestion what should I do?

**Comment by awthwathje** [comment]
Let's try this one more time.

1. Open Steam Screenshot Uploader and remove any screenshots for the "Governor of Poker 2: Premium Edition" (you have one).
2. Fully quit Steam.
3. Add one screenshot for the game ID `70210` (hopefully not previously uploaded; you can remove it afterwards. Just upload some random JPG).
4. Start Steam and check if it can be uploaded.

The thing with quitting Steam is pretty important, since it can write to `screenshots.vdf` before it exits.

**Comment by MissaCazuri** [comment]
Still error, Im going to try it later again. Other things should I note or should do later?

**Comment by awthwathje** [comment]
You can choose another (installed) game you own, and for which you have never uploaded screenshots, and try to upload some screenshot for it using SteaScree. If it will be uploadable succefully, then this issue is specific only to the `70210` game.

By the way, "Governor of Poker 2: Premium Edition" is installed, right?

**Comment by MissaCazuri** [comment]
Yes. Okay I will try those suggestion. Do the type of photo affects the outcome? Im using jpg but will using png make any difference?

**Comment by awthwathje** [comment]
So, the game "Governor of Poker 2: Premium Edition" is installed? PNGs get converted to JPG internally by SteaScree, so no, this will not make any difference.

**Comment by MissaCazuri** [comment]
Yep all of my games in my steam library are all installed in my external.

**Comment by awthwathje** [comment]
One last thing to try: open VDF-file with some text editor and set `vrfilename` value to `""` from this single entry for `70210`. So it will be like this:

```
	"0"
		{
			"type"		       "1"
			"filename"		"70210/screenshots/20171224140054_1.jpg"
			"thumbnail"		"70210/screenshots/thumbnails/20171224140054_1.jpg"
			"vrfilename"		""
			"imported"		"1"
			"width"		        "800"
			"height"		        "600"
			"gameid"		        "70210"
			"creation"		"1514206700"
			"caption"               "EZ Clap"
			"Permissions"		"8"
			"hscreenshot"		"18446744073709551615"
		}
```

It should be done with Steam exited. Once you made the modification of this file, reopen Steam and try to upload the image again.

**Comment by MissaCazuri** [comment]
Its still error, Im giving up for today, I'll try again tomorrow

**Comment by awthwathje** [comment]
Okay, I'm interested if this issue is relevant just to Governor of Poker 2: Premium Edition or to any other game.

**Comment by MissaCazuri** [comment]
It finally work. I just deleted this (F:\Steam\userdata\140883081\760\remote\70210) then I run the program, I manually typed the game ID, copy and upload the screenshot, launch steam, select the added screenshot and it finally work. I really dont know what happen but thanks for sticking with me

**Comment by awthwathje** [comment]
Cool! It was ultimately the problem with the wrong game ID `70200`. SteaScree took it from your Steam folder name (probably you managed to upload some screenshots for it in the past), then you chose it from the dropdown, and tried to upload, but you actually don't own `70200` and that's what caused the problem.

**Comment by arthurEspooner** [comment]
has nothing to do with owning the game. i had screenshots in my folder from games i had refunded or demo'd before your tool destroyed my steam.
