### ISSUE TITLE
There was an error uploading 1 screenshots. Steam Cloud may be temporary unavailable.

### ISSUE THREAD

**Issue by MissaCazuri** [awthwathje/SteaScree#22]
I was playing a game and keep pressing the f12 to take the screenshot but my shareX is also open so all of my screenshots are there. I remember this application so I tried it again. I followed the procedure and same thing happen the last time I used the application but this time I choose'd a game that is on the list ( I didnt type any game id)

**Comment by MissaCazuri** [comment]
Its fixed. What I did is delete both screenshot.vdf and screenshot.vdf.bak . Load my steam, get in game, took another screenshot. Located that screenshot, copied the named and swap it to the added screenshot by steascree (I also did the same to the thumbnail folder). Idk what cause the error and hoping to know the answer

**Comment by awthwathje** [comment]
Hello. Closing now, since there is no clear indication what went wrong and what should be fixed.
