### ISSUE TITLE
App immediately closing on launch (MacOS)

### ISSUE THREAD

**Issue by apb-hello-world** [awthwathje/SteaScree#23]
App never opens. Closes immediately. MacOS 10.13.2

Problem details: 
https://gist.github.com/alexboutros/2b7a6f5b1971bdd6590013083adea79b

**Comment by awthwathje** [comment]
Hello and thanks for reporting the issue. I can confirm that app doesn't work with a recent macOS.

Most probably Qt should be updated and this will resolve the issue.

But now I'm super-busy and, even more importantly, my development PC is in non-working condition, so I'm unable to look into the issue.

I hope I'll be able to get back on track in the next month.

**Comment by awthwathje** [comment]
Seems like I resolved the issue. I re-uploaded the new app bundle: https://steascree.download/steascree-1.5.4-macos.dmg. Now it works for me on macOS Mojave.
