### ISSUE TITLE
I think Steam has finally cracked down on uploading customs screenshots

### ISSUE THREAD

**Issue by Omarock92** [awthwathje/SteaScree#27]
Again. I'm getting the infamous upload to cloud error.

**Comment by awthwathje** [comment]
Well, I've just tried to upload a random JPG to random game (Supreme Commander II). Seems like it still works.

Maybe your game is out of Steam Store now, or the picture is too big (although in the latter case SteaScree still should resize it to the maximum allowed size).

Care to investigate a little bit more?

**Comment by Nico-0** [comment]
Same, I'm getting "Steam Cloud may be temporarily unavailable"

Solved by deleting manually vrfilename for each screenshot in screenshots.vdf
[Tutorial](https://gaming.stackexchange.com/questions/282526/new-way-to-upload-custom-screenshots-to-steam)

**Comment by awthwathje** [comment]
Closing because of the inactivity.
