### ISSUE TITLE
Software only detects one game (CSGO)

### ISSUE THREAD

**Issue by Zwizzor** [awthwathje/SteaScree#3]
Hi, this software is great, but I can only use CSGO when I have undreds of games on my account to upload the screenshots, is there a way to fix this please? When I try to add the game ID manually it doesn't work.

**Comment by awthwathje** [comment]
Hi. If SteaScree only detects a single game for your account, this means that there is just one folder with Steam screenshots for this account found on your computer.

But you can find ID of any other game you own (on the steampowered.com for example) and copy it directly into the SteaScree's "Game ID" field.

It's that easy.

Screenshot for you reference:
![Screenshot](http://i.imgur.com/znQlbNa.png)

If you do exactly this and believe, that there is a bug, feel free to reopen this issue, I'll look into what goes wrong.

**Comment by Zwizzor** [comment]
> **When I try to add the game ID manually it doesn't work.**

**Comment by awthwathje** [comment]
Okay, can you please share your screenshots.vdf file and a screenshot of SteaScree when all information is entered?

**Comment by awthwathje** [comment]
Closed for now due to the lack of a feedback from a submitter, will reopen once he will be back.
