### ISSUE TITLE
Feature Request - Update VDF file to fix broken Steam Screenshots thumbnails

### ISSUE THREAD

**Issue by JFMugen** [awthwathje/SteaScree#31]
I use Steam to take screenshots, but since Steam's screenshot window is not that good, I check/remove screenshots in the explorer. But then that creates error signs for removed screenshots. I think just an "update VDF file" button would be handy that can fix all that error signs.

**Comment by awthwathje** [comment]
The tricky part is that you never know what causes the issue and how to make it work. This whole Steam Cloud thing is totally a black box and have no documentation (it's not aimed at developers anyway).

So unfortunately it's quite a hard task and frankly outside of this app's scope.
