### ISSUE TITLE
Prepare Screenshots For Uploading Button Does Not Become Active

### ISSUE THREAD

**Issue by Euther** [awthwathje/SteaScree#32]
Good morning,

Been using SteaScree for many years... This morning I start moving files in the 21090 <F.E.A.R.> folder, and after hitting the "Copy screenshots to game directory" botton, the Prepare Screenshots For Uploading Button Does Not Become Active.

Steam was not running at the time, either.

Regards,
Euther

**Comment by Euther** [comment]
Seems having steam rebuild the screenshots.vdf file cleared the issue... however, there is now an issue of STEAM not showing the upload cloud on SSs uploaded... something fishy going one... :/

**Comment by awthwathje** [comment]
Hey there. You're right, cloud icons will be cleared if you regenerate the screenshots.vdf.
