### ISSUE TITLE
Is it expected to have "Steam cloud may be unavailable" error if we are trying to upload a screenshot for a game that we don't have, but a Steam has?

### ISSUE THREAD

**Issue by JFMugen** [awthwathje/SteaScree#33]
In my case, its GTA V. 

I just used the tool to save/upload nearly 100 screenshots (works without a problem, thanks :) but it refuses to upload GTA V screenshots. 

Only difference is, I don't have GTA V (played on EGS) but I have others. 

Is that expected?

**Comment by arthurEspooner** [comment]
don't bother with this tool, it will break your ability to upload 

https://github.com/awthwathje/SteaScree/issues?q=is%3Aissue+is%3Aclosed+error+uploading

**Comment by awthwathje** [comment]
Yes, it's expected, Steam won't allow screenshots for the games you don't own.
