### ISSUE TITLE
Tool breaks your ability to upload to steam cloud

### ISSUE THREAD

**Issue by arthurEspooner** [awthwathje/SteaScree#34]
every time i have used this tool, a few weeks later i'm unable to upload any screenshots and have to manually delete things from screenshots.vdf; i've also seen posts on various forums where people used this tool and were unable to diagnose the issue. not everyone knows how to come to github and solve it.

you should either fix the bug or take the tool down. you are breaking systems. at the least there should be a disclaimer as this is a well known issue that has never gone away.

https://github.com/awthwathje/SteaScree/issues?q=is%3Aissue+is%3Aclosed+error+uploading

https://github.com/awthwathje/SteaScree/issues/29

**Comment by arthurEspooner** [comment]
typical screenshots.vdf fix did not work this time. i had to delete all screenshots and the .vdf and then reboot. dev is MIA too, awesome.

do NOT use this.

**Comment by arthurEspooner** [comment]
whoa, the issue came back again. had to delete all screenshots and .vdfs and restart steam. my screenshots worked for 1.5 decades before using this tool. is there something possibly wrong on the actual steam cloud side? what exactly is going on here?

@awthwathje you seriously need to take this down until you can actually figure out what's going on. every thread with this issue has it basically "going away" on its own and you chalking it up to something different. if whatever you did still messes with my screenshots at this point, you have a serious issue.

**Comment by awthwathje** [comment]
I wouldn't call it "breaking systems". Steam Cloud is notoriously unstable without using any tools. On some day I can upload screenshots and on the next day I cannot upload anything and on the day after it I can upload everything again.

**Comment by awthwathje** [comment]
I wouldn't call it "breaking systems". Steam Cloud is notoriously unstable without using any tools. On some day I can upload screenshots and on the next day I cannot upload anything and on the day after it I can upload everything again.
