### ISSUE TITLE
Unclear file size / image size limits

### ISSUE THREAD

**Issue by w4hnsinn** [awthwathje/SteaScree#4]
Copying + Preparing of LARGE jpgs works fine, but then Steam Screenshot Uploader complains: "Screenshot could not be loaded" and will not let you upload said images.
I tried this with a JPG around 14 MB in size (huge resolution though, 10k by 8k).

I've verified that it would work for smaller files (reduced the above image to 10%, worked without a hitch).

//edit: Ive also just tried compressing the jpeg as hard as possible, i.e. leaving the resolution but reducing file size to some 600 KB ---> same problem. So Steam does some automated resolution checking..

**Comment by awthwathje** [comment]
I will investigate Steam limits. Thanks for reporting.

**Comment by awthwathje** [comment]
I've performed my own investigation into Steam Cloud limits and here it is. The maximum side size is 16000 pixels and the maximum resolution is somewhere near 26210175 pixels (however I can't determine the exact value, I think my estimate is in <50 pixel range).

Now, when SteaScree detects some really huge screenshot(s), a dialog window appears, just like this:

![screenshot](http://i.imgur.com/ghwA3FL.png)

You can autoresize (respecting aspect ratio of course), skip or try to upload image(s) in question and also do all of this in batch.
