### ISSUE TITLE
Not loading all Game IDs

### ISSUE THREAD

**Issue by DwayneHawkins** [awthwathje/SteaScree#6]
Hello

Thanks you for this app. You did a real fine job.
Just a problem : it does not seem to find all my games.
The userdata dictionary is found, one user ID too, and some game IDs, but not all of them.
At first I thought it was because my steam has 3 libraries, scattered around on my hard disks, but no, the game ID dropdown list is showing games from different libraries.

https://dl.dropboxusercontent.com/u/38282964/steascree.jpg

Thanks again

**Comment by DwayneHawkins** [comment]
OK, had a look at the closed issues, and I found I just need to find and type the game ID myself. It worked. Thanks and sorry for the post.

**Comment by awthwathje** [comment]
Hey. Yes, the app reads only those game IDs for which screenshots have been already taken and thus directories exist. However you can manually type in game ID. I should probably need to indicate it in the app somehow. Will do this once I'll get all the tooltips in place.
